name: "test-env"
on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        type: choice
        description: Environment
        required: true
        options:
        - development
        - production


jobs:
  test1:
    name: "test1"
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Create env file
        run: |
          cat << EOF > .env
          ### Webpack dev server ###
          CDH_QUICKSIGHT_PUBLIC_PATH=http://localhost:3001/
          PORT=3001
          DEV_SERVER_OPEN_BROWSER=false
          
          ### Env ###
          NODE_ENV=${{ secrets.NODE_ENV }}
          REACT_APP_ISOLATED_DEVELOPMENT=${{ secrets.REACT_APP_ISOLATED_DEVELOPMENT }}
          
          ### APIs (real and mocked) ###

          # real API url
          REACT_APP_CDH_QUICKSIGHT_API_URL=${{ secrets.REACT_APP_CDH_QUICKSIGHT_API_URL }}
          
          # mock API url (when run on localhost or deployed to AWS)
          REACT_APP_CDH_QUICKSIGHT_MOCK_API_URL=${{ secrets.REACT_APP_CDH_QUICKSIGHT_MOCK_API_URL }}
          
          ### UI variables ###
          REACT_APP_DASHBOARD_PARENT_ID=${{ secrets.REACT_APP_DASHBOARD_PARENT_ID }}
          REACT_APP_UNDO_TIME_MS=${{ secrets.REACT_APP_UNDO_TIME_MS }}
          
          EOF
      - name: check env file
        run: cat .env
