name: "test-env"
on:
    workflow_call:
        inputs:
            ENVIRONMENT:
                required: true
                type: string
        # type: choice
        # description: Environment
        # required: true
        # options:
        # - TEST_ENV


jobs:
  test1:
    name: "test1"
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: create env file
        run: |
           echo secret1=${{ secrets.T2 }} >> .env
           cat .env