name: "test-env"
on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        type: text
        default: TEST_ENV
        



# on:
#   workflow_dispatch:
#     inputs:
#       ENVIRONMENT:
#         type: choice
#         description: Environment
#         required: true
#         options:
#         - TEST_ENV
#         - TEST2_ENV


jobs:
  test1:
    name: "test1"
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: create env file
        run: |
           echo secret1=${{ secrets.T2 }} >> .env
           echo NODE_ENV=${{ secrets.NODE_ENV }} >> .env
           cat .env
