name: "test-env"
on: push
    # workflow_call:
    #   inputs:
    #     ENVIRONMENT:
    #       type: choice
    #       description: Environment
    #       default: 'TEST_ENV'
    #       required: true
    #       options:
    #       - TEST_ENV


jobs:
  test1:
    name: "test1"
    runs-on: ubuntu-latest
    environment: TEST_ENV #${{ inputs.ENVIRONMENT }}
    steps:
      - name: create env file
        run: |
           echo secret1=${{ secrets.T2 }} >> .env
           cat .env