name: "test-env"
on:
  push:

jobs:
  test1:
    name: "test1"
    runs-on: ubuntu-latest
    environment: test-env
    steps:
      - name: create env file
        run: |
          env
          echo ${process.env.T2}